/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppMenuBar: typeof import('./src/components/AppMenuBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListUsaha: typeof import('./src/components/ListUsaha.vue')['default']
    PetaComponent: typeof import('./src/components/PetaComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
